Add Parseable Docker Extension to suggestions
docker/hacktoberfest-2022 pull request #15
Opened 2022-09-22 13:50 UTC by nitisht

2022-09-26 14:51 UTC, gtardif approved these changes

2022-09-26 15:06 UTC, felipecruz91 requested changes
Resolve conflicts

2022-09-26 16:39 UTC, nitisht commented
> Resolve conflicts

done

2022-09-27 07:06 UTC, gtardif approved these changes

2022-09-27 07:06 UTC, merged